/* auth */
export const LOGGED_IN_USER = 'LOGGED_IN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

/* categries */
export const ALL_CATEGORIES = 'ALL_CATEGORIES'
export const ONE_CATEGORY = 'ONE_CATEGORY'
export const NEW_CATEGORY = 'NEW_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'

/* sub categries */
export const ALL_SUBCATEGORIES = 'ALL_SUBCATEGORIES'
export const ONE_SUBCATEGORY = 'ONE_SUBCATEGORY'
export const NEW_SUBCATEGORY = 'NEW_SUBCATEGORY'
export const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY'
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY'
export const SUBCATEGORY_ERROR = 'SUBCATEGORY_ERROR'